FROM ubuntu:14.04

RUN \
    apt-get update; \
    apt-get install -y python-pip python-dev libgdal-dev gdal-bin swig; \
    pip install numpy

WORKDIR /work
COPY ./ /work

RUN pip install -r requirements-dev.txt
RUN pip install .
